/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    orders: Order;
    pages: Page;
    'portfolio-entries': PortfolioEntry;
    'product-categories': ProductCategory;
    products: Product;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'portfolio-entries': PortfolioEntriesSelect<false> | PortfolioEntriesSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'shop-settings': ShopSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderRef: string;
  createdAt: string;
  customerName: string;
  customerEmail: string;
  /**
   * Total including shipping, in pence.
   */
  totalAmount: number;
  shippingCost: number;
  /**
   * Snapshot of products at time of purchase.
   */
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  fulfilmentStatus: 'pending' | 'shipped' | 'delivered' | 'requires-attention';
  /**
   * Royal Mail tracking number.
   */
  trackingNumber?: string | null;
  /**
   * Internal notes - not visible to customers.
   */
  notes?: string | null;
  stripePaymentStatus: 'pending' | 'paid' | 'failed' | 'requires-attention';
  stripeSessionId: string;
  shippingAddress:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            headline: string;
            subheadline?: string | null;
            style?: ('full' | 'short') | null;
            ctas?:
              | {
                  text: string;
                  url: string;
                  style?: ('ghost' | 'primary') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * If set, shows the before/after toggle button. Homepage only.
             */
            toggleButtonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heroBlock';
          }
        | {
            cards: {
              title: string;
              body: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceCardsBlock';
          }
        | {
            sectionHeading: string;
            maxItems?: number | null;
            linkText?: string | null;
            linkUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolioTeaserBlock';
          }
        | {
            sectionHeading?: string | null;
            showAll?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolioGridBlock';
          }
        | {
            sectionHeading: string;
            introText?: string | null;
            tiers: {
              tierName: string;
              audience: string;
              price: string;
              features: {
                feature: string;
                id?: string | null;
              }[];
              isFeatured?: boolean | null;
              ctaText?: string | null;
              ctaUrl?: string | null;
              id?: string | null;
            }[];
            linkText?: string | null;
            linkUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingSectionBlock';
          }
        | {
            headline: string;
            buttonText: string;
            buttonUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaStripBlock';
          }
        | {
            contactEmail?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSectionBlock';
          }
        | {
            /**
             * E.g. Featured Pieces
             */
            sectionHeading: string;
            maxItems?: number | null;
            /**
             * E.g. View all
             */
            linkText?: string | null;
            /**
             * E.g. /shop
             */
            linkUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productTeaserBlock';
          }
        | {
            sectionHeading?: string | null;
            /**
             * Show filter buttons above the product grid.
             */
            enableFiltering?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGridBlock';
          }
        | {
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image: number | Media;
            /**
             * Which side the image appears on.
             */
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textWithImageBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-entries".
 */
export interface PortfolioEntry {
  id: number;
  projectName: string;
  description: string;
  screenshot?: (number | null) | Media;
  liveUrl?: string | null;
  /**
   * Hex colour code for the card accent (e.g. #ff6b35)
   */
  brandColour?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  /**
   * Auto-generated from name. You can override if needed.
   */
  slug: string;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Used in product URLs.
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * First image is the main photo. Drag to reorder.
   */
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * Enter price in pence. E.g. 2500 = GBP 25.00.
   */
  price: number;
  /**
   * How many are available. Set to 0 when sold out.
   */
  stock: number;
  /**
   * Show this product in the homepage featured section.
   */
  featured?: boolean | null;
  category?: (number | null) | ProductCategory;
  /**
   * Lower numbers appear first in the shop.
   */
  sortOrder?: number | null;
  /**
   * Product code for your records.
   */
  sku?: string | null;
  /**
   * E.g. 12cm x 8cm.
   */
  dimensions?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Which client this user manages content for. Set on creation; cannot be changed afterwards.
   */
  tenant: 'betterjustice' | 'selsellspottery' | 'centrifungal';
  /**
   * Admins can manage users, delete content, and access financial records. Editors can create and update content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'portfolio-entries';
        value: number | PortfolioEntry;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderRef?: T;
  createdAt?: T;
  customerName?: T;
  customerEmail?: T;
  totalAmount?: T;
  shippingCost?: T;
  items?: T;
  fulfilmentStatus?: T;
  trackingNumber?: T;
  notes?: T;
  stripePaymentStatus?: T;
  stripeSessionId?: T;
  shippingAddress?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        heroBlock?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              style?: T;
              ctas?:
                | T
                | {
                    text?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              toggleButtonText?: T;
              id?: T;
              blockName?: T;
            };
        serviceCardsBlock?:
          | T
          | {
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        portfolioTeaserBlock?:
          | T
          | {
              sectionHeading?: T;
              maxItems?: T;
              linkText?: T;
              linkUrl?: T;
              id?: T;
              blockName?: T;
            };
        portfolioGridBlock?:
          | T
          | {
              sectionHeading?: T;
              showAll?: T;
              id?: T;
              blockName?: T;
            };
        pricingSectionBlock?:
          | T
          | {
              sectionHeading?: T;
              introText?: T;
              tiers?:
                | T
                | {
                    tierName?: T;
                    audience?: T;
                    price?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    isFeatured?: T;
                    ctaText?: T;
                    ctaUrl?: T;
                    id?: T;
                  };
              linkText?: T;
              linkUrl?: T;
              id?: T;
              blockName?: T;
            };
        ctaStripBlock?:
          | T
          | {
              headline?: T;
              buttonText?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        contactSectionBlock?:
          | T
          | {
              contactEmail?: T;
              id?: T;
              blockName?: T;
            };
        productTeaserBlock?:
          | T
          | {
              sectionHeading?: T;
              maxItems?: T;
              linkText?: T;
              linkUrl?: T;
              id?: T;
              blockName?: T;
            };
        productGridBlock?:
          | T
          | {
              sectionHeading?: T;
              enableFiltering?: T;
              id?: T;
              blockName?: T;
            };
        textWithImageBlock?:
          | T
          | {
              heading?: T;
              body?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-entries_select".
 */
export interface PortfolioEntriesSelect<T extends boolean = true> {
  projectName?: T;
  description?: T;
  screenshot?: T;
  liveUrl?: T;
  brandColour?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  price?: T;
  stock?: T;
  featured?: T;
  category?: T;
  sortOrder?: T;
  sku?: T;
  dimensions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenant?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Links shown in the main navigation bar.
   */
  navLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Short text displayed in the footer area.
   */
  footerTagline?: string | null;
  /**
   * Links shown in the site footer.
   */
  footerLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright notice shown at the bottom of the site.
   */
  copyrightText?: string | null;
  /**
   * Contact form messages and order alerts are sent here.
   */
  contactEmail?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'etsy' | 'tiktok';
        /**
         * Full URL including https://
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: number;
  /**
   * Your Stripe publishable key (starts with pk_).
   */
  stripePublicKey?: string | null;
  /**
   * Flat rate shipping in pence. E.g. 495 = GBP 4.95.
   */
  shippingCostPence: number;
  /**
   * Orders above this amount get free shipping. Set to 0 to disable.
   */
  freeShippingThresholdPence?: number | null;
  /**
   * Optional banner text shown on the shop page. E.g. All items handmade - please allow 5-7 days.
   */
  shopAnnouncementText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerTagline?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  stripePublicKey?: T;
  shippingCostPence?: T;
  freeShippingThresholdPence?: T;
  shopAnnouncementText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}